### ISSUE TITLE
Easyblogger opens w3m browser, which does not have javascript and fails to OAuth

### ISSUE THREAD

**Issue by didibus** [raghur/easyblogger#3]
On OpenSuse, when I try to run easyblogger get to authenticate myself it opens the browser inside the terminal using w3m, which does not have javascript and fails to let me OAuth, since the google page says it needs javascript.

**Comment by didibus** [comment]
I think the google oAuth2 library has a parameter: `--noauth_local_webserver` which will avoid this issue by showing a link, and waiting for the user to manually copy the link into a browser somewhere to authenticate.

**Comment by didibus** [comment]
What's strange is if I run blogger.py directly, and just create an EasyBlogger and call _OAuth_Authenticate() at the bottom, it did work, and opened in the browser and not w3m. Not sure how come.

**Comment by raghur** [comment]
>I also did not need to be root. I think root might be the issue, I never tried running easy blogger without root since I was copying from the readme.

Think this might  be it. I can't imagine why one would need to be root now :(... If you don't mind terribly, can you test it and let me know and I'll update the readme?

**Comment by didibus** [comment]
I tested it without the sudo, and it works like a charm. So you probably want to change the readme.

**Comment by wmsilva191** [comment]
To this problem i coudnt' autenticate with the parameter --noauth_local_webserver , because wasn't working.

SO, i opened 2 terminals, the first i run easyblogger --blogid {blogid} get and then the aplication show me the url, and i copy the url and access from my computer and i did the google autentication, when finished the url redirect to a localhost page.

Then i copy the url from my webbrowser and on the second terminal i just make a wget comand ponting the URL and works.

wget http://localhost:8080/?code=****************#

**Comment by raghur** [comment]
@wmsilva191 - if you're running in a DE, you don't need '--noauth-local-webserver' afaik. Just run `easyblogger --blogid <id> get` and it should open your default browser to authenticate.
