### ISSUE TITLE
--clientid and --secret args

### ISSUE THREAD

**Issue by pidugusundeep** [raghur/easyblogger#92]
I always have an issue with 'Error: redirect_uri_mismatch' what could be missing? 
```
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob,
 can only be used by a Client ID for native application.
 It is not allowed for the WEB client type. You can create a Client ID
 for native application at https://console.developers.google.com/apis/credentials/oaut
``` 
This is the exact error.

**Comment by raghur** [comment]
Can you perhaps explain what you're trying to do? You need to use your own client id/secret only if you're embedding easyblogger class in your own tool/utility OR if you just don't want to stick with the clientid/secret it's shipped with. Review this https://github.com/raghur/easyblogger#client-api-ids

Otherwise, you can just use with a get call and with your blog id - which will then open your browser and ask you to authorize access.

**Comment by pidugusundeep** [comment]
@raghur I had some issue with the redirect URL, earlier I was using the keys generated for web application and I was trying to use it in python which was the first mistake and then I generated the AUTH keys with others and it just works fine, I was able to use with blog id but was not confident enough to log in with my google account with your app so instead I was trying to use it my own client id/secret and it just works fine thanks.
